apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "cluster-ci-cache.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-agent
  labels:
    {{- include "cluster-ci-cache.labels" . | nindent 4 }}
{{- if .Values.s3Credentials.createSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3-creds
  labels:
    {{- include "cluster-ci-cache.labels" . | nindent 4 }}
type: Opaque
stringData:
  access-key: {{ .Values.s3Credentials.accessKey | quote }}
  secret-key: {{ .Values.s3Credentials.secretKey | quote }}
{{- end }}
